### ISSUE TITLE
Todo for first release

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/QuantEconHub#9]
- [x] Move the instructions, etc. from https://github.com/arnavs/quanteconhub-docker into this repo.  Maybe in a subdirectory called "google-hub" (will other ones later for the full QE managed one)
- [x] Get rid of the instructions in the main README and link to the other
- [x] Move the docker to the main QE one. name "google-hub"
- [x] Change instructions to use this, get rid of any arnavsood
- [x] Move the FAQ into its own FAQ.md.  Can categorize the sections in the FAQ.md.  Leave the customization options inside the README.md (optional customization)
- [x] Run though a final time with the new text/names.
- [x] Make sure clear near the top of the readme that this is a meter, once its on you can't really sleep it.  Think $2/day.
- [ ] Ship to florian!

**Comment by arnavs** [comment]
OK, finished my iteration on the instructions. It's a "set it and forget it" workflow, but if you needed to, you could fire up the container again to make changes (say, move to a new version of `quantecon/base` for the user notebook server, or change the whitelist, etc.) The key is to not `docker rm` the container. I elaborate on this in the FAQ. 

We also incorporated big, neon-lights warnings about pricing.

Closing now, and then @jlperla can handle the ship to Florian.
